### ISSUE TITLE
Generalize to the Y as well?

### ISSUE THREAD

**Issue by dpetrou** [mykeln/teslaprep#10]
Hello, thank you for this effort. It's unclear how much is specific to the 3. It would be nice, if possible, for this to generalize beyond the 3 and to the Y as well. Are there Y checklists that could perhaps be audited against what's here so we can curate a more general list of inspections to do? Assuming this sounds like a good idea... Thanks again, David

**Comment by mykeln** [comment]
You read my mind! I'm in the process of adapting it now.

**Comment by dpetrou** [comment]
Fantastic!

**Comment by dpetrou** [comment]
I was motivated to write after reading https://electrek.co/2020/06/16/tesla-model-y-quality-issues/

Perhaps issues listed there or to resources off that page can be included in the checklist here.

**Comment by mykeln** [comment]
I'm on it; will note the common ones that are likely going to be lasting issues for a while. The guide itself is generalized, and I'm going to split the checklists into their own files for easier printing and organization.

**Comment by mykeln** [comment]
Going to mark this as closed; I'll be adding to the model y checklist as more specific things come up, but for the most part, they are very similar. Let me know if anything stands out, and thanks for the suggestion!

**Comment by dpetrou** [comment]
Thank you Myke!

**Comment by dpetrou** [comment]
FYI, more issues are reported in the docs and videos referenced by https://insideevs.com/features/429522/video-tesla-model-y-concerns-delivery/amp/

**Comment by mykeln** [comment]
Thanks! I thought most of these were already covered under general "look for panel gaps," etc. But I added some more specificity to help new owners pay particular attention to them. I also added an entry for the trunk button close test (which wouldn't be on a 3).

**Comment by dpetrou** [comment]
Thanks Myke! I was also thinking it would be good to annotate every
specific issue as to whether or not they are serious enough that one should
/not/ take possession of the vehicle. This guide will be used under time
constraints in a showroom. As one goes through the checklist, I think it
would be helpful if it's clear for any particular issue whether one should
ask the salesperson to address the issue immediately or schedule time for a
later repair. If you agree, then there are a couple ways to do this: add
some kind of tag to each bullet, or separate the bullets into different
lists based on severity. WDYT? Happy to start a new issue if I should have.
David

**Comment by mykeln** [comment]
This is my opinion, so happy to discuss further: I mention in the doc that the only item that should warrant delivery refusal is paint. This philosophy came from the early days of the Model 3 deliveries. Virtually every issue was fixable by a later service visit _except_ paint.

Tesla seemed to hold firm with a "take it or leave it" approach on those issues. The issues in the video you cited are certainly easily fixable with an hour at the service center. Definitely not something that would warrant not taking possession.

As far as whether someone should have it addressed right then vs. a later visit, that's more of a personal preference based on the amount of time someone has available, or how busy the service center is. I don't think there's any technical distinction between having it fixed in the moment (and taking possession) vs. getting it fixed later, other than convenience.

**Comment by dpetrou** [comment]
Gotcha, Myke. Could you explain what you mean by "take it or leave it"
approach? I hope it's the case that any of the issues in the doc (except
paint) will be fixed by Tesla *free of charge* /after/ taking possession at
a later date at the service center.

In short, I think users of this document could use the peace of mind that
they can go over the bullets deliberately with no time pressure after
taking possession, at home, etc. (except for paint), and that if any issue
is found, it would be addressable at the service center free of charge. Am
I understanding that right?

Thanks,
David

**Comment by mykeln** [comment]
"Take it or leave it" meaning -- accept delivery, or don't. Specifically about paint issues. If you _insist_ that they fix the paint on the existing car, they're certainly willing to do it for free, but it'd need to be scheduled.

That said, this checklist isn't intended to guide folks on what they should/shouldn't accept. A lot of that is personal. This resource is simply to draw one's attention to what they should check.

Your understanding is correct; virtually any issue is addressable at the service center, for free (including paint). The only issue that would require them taking the car apart to fix would be paint, which is a pretty good objective reason to not take delivery.

**Comment by dpetrou** [comment]
Fantastic. Another objective reason to not take delivery on paint issues I
suppose would be because it might be hard to convince them the paint issue
existed prior to taking possession.

In any case, I no longer think my suggestion makes sense. I was concerned
that in the moment any buyer might be rushed and unable to diligently go
through the checklist in the showroom, and so a priority order would be
useful. But one can simply go through everything (except paint) at their
own pace later.

Thanks again,
David

**Comment by mykeln** [comment]
Well said! I agree with your observation about feeling "rushed." I certainly did. I'll add a reminder that folks can take their time.
