### ISSUE TITLE
Tesla 'T' is gone; frunk mat?

### ISSUE THREAD

**Issue by EasternPA** [mykeln/teslaprep#19]
It goes without saying this is an awesome list and is well-respected in the community. Some things have changed with the UI, though. Most notably the Tesla 'T' is gone from the top center of the main screen. I also saw mention of inspecting the tow hook under the frunk mat on the Model Y. Is there still a frunk mat in the Y? My 2020 Model 3 LR did not come with one.

Thanks!

**Comment by mykeln** [comment]
This is great feedback. I will update the docs to find the proper area since the Tesla T is gone. I'll also adjust the reference to the "frunk mat"

**Comment by EasternPA** [comment]
As this just appeared in Reddit again, I reviewed it again. When you corrected this issue, you described the car icon as being in the bottom right. It is at the far left end of the main menu that runs along the bottom. 

Thanks!

**Comment by mykeln** [comment]
Thanks, this is fixed!

Myke
