### ISSUE TITLE
This app has reached its rows limit

### ISSUE THREAD

**Issue by milindrao** [mykeln/teslaprep#33]
Getting an error stating "This app has reached its rows limit" when I click on https://teslaprep.glideapp.io/ Both on the web page and while attempting to install on my Pixel 6

**Comment by mykeln** [comment]
thanks! This should be fixed

**Comment by milindrao** [comment]
I'm afraid not. Even in Incognito mode.

**Comment by josh-vincent** [comment]
bump - hitting the "This app has reached its rows limit" error again

**Comment by mykeln** [comment]
Should be fixed for the long-term now. Sorry for the inconvenience!

**Comment by acorkin** [comment]
@mykeln just bumping this again as the message "This app has reached its rows limit" is coming up on the app again.

**Comment by iamavneetsingh** [comment]
@mykeln bumping the issue started to pop again.
